# Generated by Django 5.1.4 on 2025-12-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('tickets', '0027_resolution_feedback_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ticket',
            field=models.OneToOneField(blank=True, help_text='The ticket this chat room is associated with (for ticket chats only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('ticket', 'Ticket Chat')], default='direct', max_length=10),
        ),
    ]
