# Generated by Django 5.1.4 on 2025-10-27 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_project_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('blocks', 'Blocks'), ('is_blocked_by', 'Is Blocked By'), ('relates_to', 'Relates To'), ('duplicates', 'Duplicates'), ('is_duplicated_by', 'Is Duplicated By'), ('causes', 'Causes'), ('is_caused_by', 'Is Caused By')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issue_links', to=settings.AUTH_USER_MODEL)),
                ('source_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_links', to='tickets.ticket')),
                ('target_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_links', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('source_ticket', 'target_ticket', 'link_type')},
            },
        ),
    ]
