# Generated by Django 5.1.4 on 2025-10-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_company_ticket_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies associated with this project', related_name='projects', to='tickets.company'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Optional: Client company this ticket is specific to. Leave blank for general project tickets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.company'),
        ),
    ]
