# Generated by Django 5.1.4 on 2025-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_add_project_companies_and_make_ticket_company_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text='Company phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email for this company', max_length=254, null=True),
        ),
    ]
