# Generated by Django 5.1.4 on 2025-11-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project_number',
            field=models.IntegerField(blank=True, help_text='Project-scoped ticket number (e.g., 1, 2, 3 for TICK-1, TICK-2, TICK-3)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('project', 'project_number')},
        ),
    ]
