# Generated by Django 5.1.4 on 2025-11-13 10:53

from django.db import migrations


def backfill_project_numbers(apps, schema_editor):
    """Backfill project_number for existing tickets"""
    Ticket = apps.get_model('tickets', 'Ticket')
    Project = apps.get_model('tickets', 'Project')
    
    # Process each project separately
    for project in Project.objects.all():
        # Get all tickets for this project, ordered by creation date
        tickets = Ticket.objects.filter(project=project).order_by('created_at')
        
        # Assign sequential numbers
        for index, ticket in enumerate(tickets, start=1):
            ticket.project_number = index
            ticket.save(update_fields=['project_number'])
    
    print(f"Backfilled project_number for {Ticket.objects.count()} tickets across {Project.objects.count()} projects")


def reverse_backfill(apps, schema_editor):
    """Reverse migration - set all project_numbers to None"""
    Ticket = apps.get_model('tickets', 'Ticket')
    Ticket.objects.all().update(project_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_project_number_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.RunPython(backfill_project_numbers, reverse_backfill),
    ]
