# Generated by Django 4.2.5 on 2025-11-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_company_name_nonunique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['column', 'column_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='column_order',
            field=models.IntegerField(default=0, help_text='Order of ticket within its column for kanban board'),
        ),
    ]
