# Generated by Django 4.2.5 on 2025-11-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_add_ticket_column_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPosition',
            fields=[
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='position', serialize=False, to='tickets.ticket')),
                ('order', models.IntegerField(default=0, help_text='Position within column (0-based)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_positions', to='tickets.column')),
            ],
            options={
                'verbose_name': 'Ticket Position',
                'verbose_name_plural': 'Ticket Positions',
                'ordering': ['column', 'order'],
                'indexes': [models.Index(fields=['column', 'order'], name='tickets_tic_column__63df5d_idx'), models.Index(fields=['updated_at'], name='tickets_tic_updated_15dd3b_idx')],
            },
        ),
    ]
