# Generated by Django 4.2.5 on 2025-11-19 18:55

from django.db import migrations


def populate_ticket_positions(apps, schema_editor):
    """
    Populate TicketPosition table from existing Ticket.column_order values.
    This migration copies position data from the Ticket model to the new
    lightweight TicketPosition model.
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    TicketPosition = apps.get_model('tickets', 'TicketPosition')
    
    # Get all tickets with their current positions
    tickets = Ticket.objects.all().select_related('column')
    
    # Create position records in bulk
    positions = []
    for ticket in tickets:
        positions.append(TicketPosition(
            ticket_id=ticket.id,
            column_id=ticket.column_id,
            order=ticket.column_order
        ))
    
    # Bulk create all positions
    if positions:
        TicketPosition.objects.bulk_create(positions, batch_size=1000)
        print(f"Created {len(positions)} ticket positions")


def reverse_populate(apps, schema_editor):
    """
    Reverse migration - delete all TicketPosition records.
    Data can be regenerated from Ticket.column_order.
    """
    TicketPosition = apps.get_model('tickets', 'TicketPosition')
    count = TicketPosition.objects.count()
    TicketPosition.objects.all().delete()
    print(f"Deleted {count} ticket positions")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticketposition'),
    ]

    operations = [
        migrations.RunPython(populate_ticket_positions, reverse_populate),
    ]
