# Generated by Django 4.2.5 on 2025-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_tickethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type', max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail', null=True, upload_to='company_logos/thumbs/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(help_text='Max 10MB. Allowed: images, PDF, Office docs, text, archives.', upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (max 5MB, JPG/PNG/GIF/WebP)', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('comment_added', 'Comment Added'), ('mention', 'Mentioned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('chat_message', 'Chat Message'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
