# Generated by Django 4.2.5 on 2025-11-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_add_logo_thumbnail_and_attachment_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, help_text='Company logo (max 5MB, JPG/PNG/GIF/WebP/SVG)', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail (not generated for SVG)', null=True, upload_to='company_logos/thumbs/'),
        ),
    ]
