# Generated by Django 4.2.5 on 2025-12-02 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_change_company_logo_to_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_feedback',
            field=models.TextField(blank=True, help_text='Customer feedback on resolution'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_rating',
            field=models.IntegerField(blank=True, help_text='Customer satisfaction rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer submitted review', null=True),
        ),
    ]
