# Generated by Django 4.2.5 on 2025-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_add_status_system'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'ticket_status'], name='tickets_tic_project_bdd910_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'ticket_status', 'rank'], name='tickets_tic_project_1e3eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_status', 'rank'], name='tickets_tic_ticket__ce6ffe_idx'),
        ),
    ]
