# Generated by Django 4.2.5 on 2025-12-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_ticket_tickets_tic_project_bdd910_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_status',
            field=models.CharField(choices=[('none', 'None'), ('awaiting_review', 'Awaiting Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', help_text='Status of the resolution review process', max_length=20),
        ),
    ]
