# Generated by Django 5.1.4 on 2026-01-08 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_resolution_feedback_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, help_text='Private feedback notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project context for this review', on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='tickets.project')),
                ('reviewer', models.ForeignKey(help_text='The admin/superadmin who created this review', on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, help_text='Optional: Link review to specific ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to='tickets.ticket')),
                ('user', models.ForeignKey(help_text='The user being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ticket__isnull', False)), fields=('reviewer', 'user', 'ticket'), name='unique_review_per_ticket')],
            },
        ),
    ]
