# Generated by Django 5.2.9 on 2026-01-29 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_add_user_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default KPI Configuration', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_configs', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(help_text='Project this KPI configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='kpi_config', to='tickets.project')),
            ],
            options={
                'verbose_name': 'KPI Configuration',
                'verbose_name_plural': 'KPI Configurations',
            },
        ),
        migrations.CreateModel(
            name='KPIIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(help_text='Key matching AVAILABLE_INDICATORS in kpi_constants.py', max_length=50)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Point weight for this indicator (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='tickets.kpiconfig')),
            ],
            options={
                'verbose_name': 'KPI Indicator',
                'verbose_name_plural': 'KPI Indicators',
                'ordering': ['order'],
                'unique_together': {('config', 'metric_key')},
            },
        ),
    ]
