# Generated by Django 5.2.9 on 2026-01-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_kpiconfig_kpiindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiindicator',
            name='threshold_green',
            field=models.FloatField(blank=True, help_text='Raw value that scores 100%. E.g. 20 tickets resolved.', null=True),
        ),
        migrations.AddField(
            model_name='kpiindicator',
            name='threshold_red',
            field=models.FloatField(blank=True, help_text='Raw value that scores 0%. E.g. 0 tickets resolved.', null=True),
        ),
    ]
